### ISSUE TITLE
Failed to publish nuget package

### ISSUE THREAD

**Issue by jjxtra** [Polly-Contrib/Polly.Contrib.DuplicateRequestCollapser#4]
Got the build working, but now it is failing to find an `Authors` element in the nuget package, even though that element exists in the csproj file. Still investigating...

Error:
https://ci.appveyor.com/project/Polly-Contrib/polly-contrib-duplicaterequestcollapser/builds/30825948/messages

Related Issue:
https://github.com/NuGet/Home/issues/7656

**Comment by jjxtra** [comment]
@reisenberger I'm stuck on this one, apparently this is by design... was the v0.1.0 nuget published manually?

**Comment by reisenberger** [comment]
Yes. Published v0.2.0 manually now.
